version: '3.8'

services:
  backend:
    build:
      context: ./backend  # Path to backend directory
      dockerfile: Dockerfile
    image: datamimicai-backend:latest
    ports:
      - "8000:8000"
    volumes:
      # - ./uploads:/app/uploads  # Maps project root uploads/ to container
      # - ./backend/src:/app/src  # Maps backend src code
      - ./backend:/backend
    environment:
      - ENV=development
      - DATABASE_URL=postgresql://synthadmin:password123@dpg-cn5s6vscn0vc739somqg-a/synthdata
      - UPLOAD_DIR=/src/uploads

  frontend:
    build:
      context: ./frontend  # Path to frontend directory
      dockerfile: Dockerfile
    image: datamimicai-frontend:latest
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app  # Maps frontend code
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend