version: "3.8"

services:
  backend:
    # Mount local source for hot reload
    volumes:
      - ./backend:/backend:rw
    environment:
      - PORT=${BACKEND_PORT:-8000}
      - BACKEND_MODULE=${BACKEND_MODULE:-src.api.main:app}
      - ENV=development
    command: ["sh", "-c", "uvicorn ${BACKEND_MODULE:-src.api.main:app} --host 0.0.0.0 --port ${PORT:-8000} --reload"]

  frontend:
    volumes:
      - ./frontend:/app:rw
    environment:
      - STREAMLIT_SERVER_PORT=${STREAMLIT_SERVER_PORT:-8501}
      - ENV=development
      - BACKEND_URL=${BACKEND_URL:-http://host.docker.internal:${BACKEND_PORT:-8000}}
    command: ["sh", "-c", "streamlit run app.py --server.address=0.0.0.0 --server.port ${STREAMLIT_SERVER_PORT:-8501}"]
