# render.yaml
services:
  - type: web
    name: datamimicai-backend
    plan: free
    runtime: python
    buildCommand: |
      pip install -r backend/requirements.txt
    startCommand: |
      uvicorn src.api.main:app --host 0.0.0.0 --port 8000
    workingDirectory: backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: datamimicai-db
          property: connectionString
      - key: UPLOAD_DIR
        value: /data
      - key: PYTHONPATH
        value: /opt/render/project/src

  - type: web
    name: datamimicai-frontend
    plan: free
    runtime: python
    buildCommand: |
      pip install -r frontend/requirements.txt
    startCommand: |
      streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    workingDirectory: frontend
    envVars:
      - key: API_URL
        value: https://datamimicai-backend.onrender.com

databases:
  - name: datamimicai-db
    plan: free
    databaseName: synthetic_data_1ag5
    user: synthadmin
