# render.yaml
services:
  - type: web
    name: datamimicai-backend
    plan: free
    runtime: python
    buildCommand: |
      cd backend && \
      pip install --upgrade pip && \
      pip install -r requirements.txt
    startCommand: |
      cd backend && \
      uvicorn src.api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: datamimicai-db
          property: connectionString
      - key: UPLOAD_DIR
        value: ./uploads
      - key: PYTHONPATH
        value: ./src

  - type: web
    name: datamimicai-frontend
    plan: free
    runtime: python
    buildCommand: |
      cd frontend && \
      pip install --upgrade pip && \
      pip install -r requirements.txt
    startCommand: |
      cd frontend && \
      streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: API_URL
        value: https://datamimicai-backend.onrender.com

databases:
  - name: datamimicai-db
    plan: free
    databaseName: synthetic_data_1ag5
    user: synthadmin
