# render.yaml
services:
  - type: web
    name: datamimicai-backend
    plan: free
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip uninstall -y torchaudio torchdata
      pip install -r backend/requirements.txt
    startCommand: |
      cd backend && \
      uvicorn src.api.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHON_VERSION # Add this line to specify Python version
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: datamimicai-db
          property: connectionString
      - key: UPLOAD_DIR
        value: /opt/render/project/uploads/
      - key: PYTHONPATH
        value: /opt/render/project/backend/

  - type: web
    name: datamimicai-frontend
    plan: free
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r frontend/requirements.txt
    startCommand: |
      cd frontend && \
      streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: PYTHON_VERSION # Add this line to specify Python version
        value: 3.11.9
      - key: API_URL
        value: https://datamimicai-backend.onrender.com

databases:
  - name: datamimicai-db
    plan: free
    databaseName: synthetic_data_1ag5
    user: synthadmin
