"""
Validation API - FastAPI Endpoints for Validation Results.

This module provides REST API endpoints for accessing validation results
generated by the ValidationFeedbackLoop. It exposes validation data for
the Decision Report UI.

Endpoints:
- GET /api/validation/decision-report/{plan_id} - Retrieve validation results

Author: DataMimicAI Team
Date: February 6, 2026
"""

from fastapi import APIRouter, HTTPException, Path
from typing import Dict, Any
import logging

from src.core.validation.validation_storage import get_validation_store

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/validation", tags=["validation"])


@router.get("/decision-report/{plan_id}")
async def get_decision_report(
    plan_id: str = Path(..., description="Plan ID to retrieve validation results for")
) -> Dict[str, Any]:
    """
    Retrieve validation results for a specific plan.
    
    This endpoint returns the validation report generated by ValidationFeedbackLoop
    after a transformation plan was executed. It shows before/after metrics and deltas.
    
    Parameters
    ----------
    plan_id : str
        The plan identifier (e.g., "TP-001")
    
    Returns
    -------
    Dict[str, Any]
        Validation report containing:
        - plan_id: Plan identifier
        - validation_results: List of metric comparisons
        - summary: Summary statistics
    
    Raises
    ------
    HTTPException 404
        If no validation results exist for the given plan_id
    HTTPException 400
        If plan_id is invalid
    
    Examples
    --------
    GET /api/validation/decision-report/TP-001
    
    Response:
    {
        "plan_id": "TP-001",
        "validation_results": [
            {
                "metric": "skewness",
                "column": "income",
                "before": 2.1,
                "after": 0.6,
                "delta": -1.5,
                "status": "SUCCESS",
                "error": null
            }
        ],
        "summary": {
            "metrics_compared": 12,
            "columns_affected": 5
        }
    }
    """
    # Validate plan_id
    if not plan_id or not isinstance(plan_id, str) or len(plan_id.strip()) == 0:
        logger.warning(f"Invalid plan_id received: {plan_id}")
        raise HTTPException(
            status_code=400,
            detail="Invalid plan_id. Must be a non-empty string."
        )
    
    # Retrieve validation results from store
    store = get_validation_store()
    validation_report = store.get_validation_result(plan_id)
    
    # Check if results exist
    if validation_report is None:
        logger.info(f"No validation results found for plan_id={plan_id}")
        raise HTTPException(
            status_code=404,
            detail=f"Validation results not found for plan_id: {plan_id}. "
                   f"Results may not have been generated yet or the plan_id is incorrect."
        )
    
    logger.info(f"Retrieved validation results for plan_id={plan_id}")
    return validation_report


@router.get("/plans")
async def list_validation_plans() -> Dict[str, Any]:
    """
    List all plan IDs that have validation results.
    
    This endpoint returns a list of all plan_ids with stored validation results.
    Useful for debugging or building a plan selection UI.
    
    Returns
    -------
    Dict[str, Any]
        Dictionary containing:
        - plan_ids: List of plan identifiers
        - count: Number of plans
    
    Examples
    --------
    GET /api/validation/plans
    
    Response:
    {
        "plan_ids": ["TP-001", "TP-002", "TP-003"],
        "count": 3
    }
    """
    store = get_validation_store()
    plan_ids = store.list_plan_ids()
    
    logger.info(f"Listed {len(plan_ids)} plans with validation results")
    
    return {
        "plan_ids": sorted(plan_ids),  # Sorted for consistency
        "count": len(plan_ids)
    }
