"""
Validation Results Storage - In-Memory Store for Validation Reports.

This module provides a simple in-memory storage for validation results
generated by the ValidationFeedbackLoop. It serves as the data layer
for the validation API endpoint.

Design:
- In-memory dictionary keyed by plan_id
- Thread-safe operations
- Simple get/set/delete interface

Author: DataMimicAI Team
Date: February 6, 2026
"""

from typing import Dict, Optional
from threading import Lock
import logging

logger = logging.getLogger(__name__)


class ValidationResultsStore:
    """
    In-memory store for validation results.
    
    This is a simple singleton store that holds validation reports
    indexed by plan_id. Results are stored as dictionaries (already
    serialized from ValidationReport.to_dict()).
    
    Thread-safe for concurrent access.
    """
    
    def __init__(self):
        """Initialize the validation results store."""
        self._store: Dict[str, Dict] = {}
        self._lock = Lock()
        logger.info("ValidationResultsStore initialized (in-memory)")
    
    def store_validation_result(self, plan_id: str, validation_report_dict: Dict) -> None:
        """
        Store a validation result.
        
        Parameters
        ----------
        plan_id : str
            Plan identifier
        validation_report_dict : Dict
            Validation report as dictionary (from ValidationReport.to_dict())
        
        Raises
        ------
        ValueError
            If plan_id is empty or validation_report_dict is not a dict
        """
        if not plan_id or not isinstance(plan_id, str):
            raise ValueError("plan_id must be a non-empty string")
        
        if not isinstance(validation_report_dict, dict):
            raise ValueError("validation_report_dict must be a dictionary")
        
        with self._lock:
            self._store[plan_id] = validation_report_dict
            logger.info(f"Stored validation result for plan_id={plan_id}")
    
    def get_validation_result(self, plan_id: str) -> Optional[Dict]:
        """
        Retrieve a validation result by plan_id.
        
        Parameters
        ----------
        plan_id : str
            Plan identifier
        
        Returns
        -------
        Dict | None
            Validation report dictionary if found, None otherwise
        """
        if not plan_id or not isinstance(plan_id, str):
            return None
        
        with self._lock:
            return self._store.get(plan_id)
    
    def delete_validation_result(self, plan_id: str) -> bool:
        """
        Delete a validation result.
        
        Parameters
        ----------
        plan_id : str
            Plan identifier
        
        Returns
        -------
        bool
            True if result was deleted, False if not found
        """
        if not plan_id or not isinstance(plan_id, str):
            return False
        
        with self._lock:
            if plan_id in self._store:
                del self._store[plan_id]
                logger.info(f"Deleted validation result for plan_id={plan_id}")
                return True
            return False
    
    def list_plan_ids(self) -> list:
        """
        List all plan_ids with stored validation results.
        
        Returns
        -------
        list
            List of plan_id strings
        """
        with self._lock:
            return list(self._store.keys())
    
    def clear_all(self) -> int:
        """
        Clear all stored validation results.
        
        Returns
        -------
        int
            Number of results cleared
        """
        with self._lock:
            count = len(self._store)
            self._store.clear()
            logger.info(f"Cleared all validation results ({count} total)")
            return count


# Global singleton instance
_validation_store = ValidationResultsStore()


def get_validation_store() -> ValidationResultsStore:
    """
    Get the global validation results store.
    
    Returns
    -------
    ValidationResultsStore
        The singleton validation store instance
    """
    return _validation_store
